### ISSUE TITLE
Change the way the template incorporates Git

### ISSUE THREAD

**Issue by peterdresslar** [ardatan/graphql-cli-fullstack-template#4]
Should the template omit .git files and allow the end user to decide on their own SCM workflow?

**Comment by peterdresslar** [comment]
Hey my mistake you are totally right.

**Comment by wtrocki** [comment]
@peterdresslar I meant that this is valid point and I just suggested the - how part.

**Comment by peterdresslar** [comment]
Reopened to discuss!

**Comment by ardatan** [comment]
`.git` is removed right now
